### ISSUE TITLE
Aggiungere una funzione standard `custom` su tutti i componenti.

### ISSUE THREAD

**Issue by alessiosantangelo** [primait/pyxis-components#26]
La necessità di personalizzazione dei componenti `Pyxis` dovrebbe permettere il passaggio di `Html.Attributes msg` extra a ogni singolo `component`. 

La funzione standard da usare è `MyModule.custom ...`

**AZIONI**
- Censire tutti i componenti attualmente sprovvisti di questa funzione. 
- Aggiungere la funzione mantenendo uno standard `cross-component` per migliorare la predittività di utilizzo.

**Comment by komlanvi** [comment]
Prendendo l'esempio del component `Prima.Pyxis.Button`, intendi una cosa di questo genere?

`custom : Scheme -> Emphasis -> Size -> String -> msg -> List (Html.Attribute msg) -> Config msg`

dove `List (Html.Attribute msg)` (il sesto argomento della funzione `custom`)  verrà mergiato con gli attributi già esistenti della funzione `button` chiamato nel `render`.

**Comment by alessiosantangelo** [comment]
@komlanvi si l'idea è quella ma abbiamo deciso per un rewriting più pesante delle `api` :)

**Comment by komlanvi** [comment]
Grazie della risposta @alessiosantangelo . Aspetto allora il gli spec del rewriting per vedere come posso contribuire.
